=== cnsuhao/Log-Cutter-oschina/doc/log-cutter-cfg-2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.jessma.org"
	xmlns:tns="http://www.jessma.org" elementFormDefault="qualified">
	<element name="CONFIG">
		<complexType>
			<sequence>
				<element name="global" maxOccurs="1" minOccurs="0">
					<complexType>
						<sequence>
							<element name="start-check-delay" maxOccurs="1" minOccurs="0">
								<simpleType>
									<restriction base="string">
										<pattern value="(0|[1-9][0-9]*|([0-2]?[0-9]\:[0-5]?[0-9]))?"></pattern>
									</restriction>
								</simpleType>
							</element>
							<element name="check-interval" maxOccurs="1" minOccurs="0">
								<simpleType>
									<restriction base="string">
										<pattern value="([1-9][0-9]*)?"></pattern>
									</restriction>
								</simpleType>
							</element>
							<element name="log4j-config-file" maxOccurs="1" minOccurs="0">
								<simpleType>
									<restriction base="string"></restriction>
								</simpleType>
							</element>
							<element name="lock-file" maxOccurs="1" minOccurs="0">
								<simpleType>
									<restriction base="string"></restriction>
								</simpleType>
							</element>
						</sequence>
					</complexType>
				</element>
				<element name="delete-files" maxOccurs="unbounded" minOccurs="0">
					<complexType>
						<sequence>
							<element name="file" maxOccurs="unbounded" minOccurs="0">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="path" use="required">
												<simpleType>
													<restriction
														base="string">
														<minLength
															value="1">
														</minLength>
													</restriction>
												</simpleType>
											</attribute>
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
						<attribute name="expire">
							<simpleType>
								<restriction base="string">
									<pattern value="([1-9][0-9]*)?"></pattern>
								</restriction>
							</simpleType>
						</attribute>
					</complexType>
				</element>
				<element name="cut-files" maxOccurs="unbounded" minOccurs="0">
					<complexType>
						<sequence>
							<element name="file" maxOccurs="unbounded" minOccurs="0">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="path" use="required">
												<simpleType>
													<restriction
														base="string">
														<minLength
															value="1">
														</minLength>
													</restriction>
												</simpleType>
											</attribute>
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
						<attribute name="threshold">
							<simpleType>
								<restriction base="string">
									<pattern value="([1-9][0-9]*)?"></pattern>
								</restriction>
							</simpleType>
						</attribute>
						<attribute name="reserve">
							<simpleType>
								<restriction base="string">
									<pattern value="([1-9][0-9]*)?"></pattern>
								</restriction>
							</simpleType>
						</attribute>
					</complexType>
				</element>
				<element name="archive-files" maxOccurs="unbounded" minOccurs="0">
					<complexType>
						<sequence>
							<element name="file" maxOccurs="unbounded" minOccurs="0">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="path" use="required">
												<simpleType>
													<restriction
														base="string">
														<minLength
															value="1">
														</minLength>
													</restriction>
												</simpleType>
											</attribute>
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
						<attribute name="expire">
							<simpleType>
								<restriction base="string">
									<pattern value="([1-9][0-9]*)?"></pattern>
								</restriction>
							</simpleType>
						</attribute>
						<attribute name="archive-path" use="required">
							<simpleType>
								<restriction base="string">
									<minLength value="1"></minLength>
								</restriction>
							</simpleType>
						</attribute>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== cnsuhao/Log-Cutter-oschina/conf/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<CONFIG	xmlns="http://www.jessma.org"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.jessma.org http://www.jessma.org/schema/log-cutter-cfg-2.0.xsd">
	<global>
		<!-- 开始日志检查延时 (小时), 默认: 0 (立刻开始)
		
			1) 当指定为一个整数值时，执行器首次启动延时时间为该值设定的小时数

				（例如：12 小时后首次启动执行器）
				<start-check-delay>12</start-check-delay>
				
			2) 当指定为一个 ‘hh:mm’ 格式的值时，执行器首次启动时间为该时分值

				（例如：12 点 34 分首次启动执行器，如果当前时间超过 12 点 34 分则在明天的 12 点 34 分首次启动执行器）
				<start-check-delay>12:34</start-check-delay>
		-->
		<!-- 02 点 30 分首次启动执行器 -->
		<start-check-delay>02:30</start-check-delay>
		<!-- 日志检查间隔 (小时), 默认: 72 -->
		<check-interval></check-interval>
		<!-- Log4J 配置文件, 默认: ${CLASS_ROOT}/../conf/log4j2.xml -->
		<log4j-config-file></log4j-config-file>
		<!-- 进程锁文件, 默认: ${CLASS_ROOT}/../${APP_NAME}.lock -->
		<lock-file></lock-file>
	</global>
	
	<!-- 要删除的日志文件列表（可配置多个，由 DelFileRunner 执行）
		1) DelFileRunner 会递归删除符合条件的文件夹及其中的所有文件
		2) 注意：在判断是否删除文件夹时，检测的是文件夹的最后修改时间，而不是其中文件的最后修改时间
		3) DelFileRunner 适用于清理 “定期产生新日志文件” 的应用程序日志
	-->
	<!-- delete-files.expire: 日志文件过期时间(天), 默认: 90 -->
	<delete-files expire="30">
		<!-- file.path: 文件所在目录, 必须填写, 不能包含通配符 -->
		<!-- file: 文件或文件夹名称, 必须填写, 可包含通配符 -->
		<file path="D:\LogCutter\logs">*.log</file>
		<file path="D:\hMailServer\Logs">*.log</file>
		<file path="D:\Tomcat 6.0\logs">*.log</file>
	</delete-files>
	<delete-files expire="365">
		<file path="E:\backup">*</file>
	</delete-files>
	
	<!-- 要截断的日志文件列表（可配置多个，由 CutFileRunner 执行）
		1) CutFileRunner 只会扫描符合条件的文件，不会扫描文件夹
		2) CutFileRunner 会截断文件的前部内容，保留后部内容
		3) CutFileRunner 适用于清理 “日志文件不断追加增长” 的应用程序日志
	-->
	<!-- cut-files.threshold:	日志文件截断阀值(KB), 默认: 10240 -->
	<!-- cut-files.reserve:		日志文件保留内容(KB), 默认: 1024 -->
	<!--
		 <!注!> 'cut-files.reserve' 是保留内容的近似值, 实际内容按行取整保留
			如下列日志文件内容:
				...... ...... ......
		 		line1: xxxxxxxxxxxxxxxxxxxxx
		 		line2: xxxxxxxxxxPyyyyyyyyyy
		 		line3: zzzzzzzzzzzzzzzzzzzzz
		 		line4: zzzzzzzzzzzzzzzzzzzzz
		 		...... ...... ...... (EOF)
		 	'P'为定位得到的保留起点, 程序实际会在'P'点开始查找下一个换行符,
		 	从该换行符的后一个字符开始保留, 也就是从第三行开始保留到文件末尾
	-->
	<cut-files threshold="10240" reserve="512">
		<file path="D:\Apache-2.2\logs">*.log</file>
		<file path="D:\MySQL Server 5.1\data">*.err</file>
	</cut-files>
	
	<!-- 要归档的日志文件列表（可配置多个，由 ArcFileRunner 执行）
		1) ArcFileRunner 把符合条件的文件或文件夹压缩归档到指定目录，并删除原文件或文件夹
		2) 归档文件格式：{原文件/文件夹名称}_{系统时间}.zip
		3) 注意：在判断是否归档文件夹时，检测的是文件夹的最后修改时间，而不是其中文件的最后修改时间
		4) ArcFileRunner 适用于清理 “定期产生新日志文件或日志目录” 的应用程序日志
	-->
	<!-- archive-files.expire:			日志文件过期时间(天), 默认: 90 -->
	<!-- archive-files.archive-path:	日志文件归档目录 -->
	<archive-files expire="120" archive-path="E:\backup">
		<file path="D:\MySQL Server 5.1\data">mysql-bin.*</file>
	</archive-files>
</CONFIG>
